#!/usr/bin/env php
<?php

require(__DIR__ . '/bootstrap.php');
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/environment.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

try {
    $application = new yii\console\Application($config);
    $exitCode = $application->run();
    exit($exitCode);
} catch (\Exception $e) {
    echo $e->getMessage() . "\n";
    exit($e->getCode());
}
